# Generated by Django 2.0.7 on 2018-07-18 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmeeting',
            name='apps_approved',
        ),
        migrations.RemoveField(
            model_name='catmeeting',
            name='apps_escalated',
        ),
        migrations.RemoveField(
            model_name='catmeeting',
            name='apps_rejected',
        ),
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2018, 7, 19)),
        ),
    ]
