# Generated by Django 2.0.7 on 2018-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0002_auto_20180719_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='catmeeting',
            name='agenda_item_apps',
            field=models.ManyToManyField(related_name='agenda_item_apps', to='assess.Application'),
        ),
    ]
