# Generated by Django 2.0.7 on 2018-07-31 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0007_auto_20180724_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(default=1.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='version',
            field=models.CharField(default=1.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2018, 7, 31)),
        ),
    ]
