# Generated by Django 2.0.7 on 2018-08-18 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0009_auto_20180818_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='catmeeting',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='assess_status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Submitted'), ('A', 'Assessing'), ('R', 'Rejected'), ('P', 'Approved'), ('E', 'Escalated'), ('I', 'IPSG Approved'), ('X', 'IPSG Rejected')], default='N', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2018, 8, 19)),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='assess_status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Submitted'), ('A', 'Assessing'), ('R', 'Rejected'), ('P', 'Approved'), ('E', 'Escalated'), ('I', 'IPSG Approved'), ('X', 'IPSG Rejected')], default='N', max_length=1, verbose_name='Status'),
        ),
    ]
